python3 scripts/freqUsed/spiral_min.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/ stackoverflow_electronics wavemap_2_664_2.json wavemap_3_1320_1.json wavemap_6_169_1.json wavemap_3_17881_1.json wavemap_5_38_1.json wavemap_13_5607_1.json wavemap_4_179_1.json wavemap_1_568_4.json wavemap_9_3097_1.json wavemap_18_11_1.json wavemap_1_7607_4.json wavemap_1_4738_30.json wavemap_2_552_1.json wavemap_32_3_1.json wavemap_7_13363_2.json wavemap_1_17795_20.json wavemap_5_12699_1.json wavemap_2_16614_1.json wavemap_11_23_1.json wavemap_76_87_1.json wavemap_51_18_1.json wavemap_8_3_1.json > /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/SPIRAL.txt
python3 scripts/freqUsed/building.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_2_664_2.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_2_664_2_floor.txt /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_2_664_2_color.txt 0.07471521690261543
python3 scripts/freqUsed/building.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_3_1320_1.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_3_1320_1_floor.txt /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_3_1320_1_color.txt 0.07471521690261543
python3 scripts/freqUsed/building.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_6_169_1.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_6_169_1_floor.txt /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_6_169_1_color.txt 0.07471521690261543
python3 scripts/freqUsed/building.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_3_17881_1.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_3_17881_1_floor.txt /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_3_17881_1_color.txt 0.07471521690261543
python3 scripts/freqUsed/building.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_5_38_1.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_5_38_1_floor.txt /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_5_38_1_color.txt 0.07471521690261543
python3 scripts/freqUsed/building.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_13_5607_1.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_13_5607_1_floor.txt /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_13_5607_1_color.txt 0.07471521690261543
python3 scripts/freqUsed/building.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_4_179_1.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_4_179_1_floor.txt /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_4_179_1_color.txt 0.07471521690261543
python3 scripts/freqUsed/building.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_1_568_4.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_1_568_4_floor.txt /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_1_568_4_color.txt 0.07471521690261543
python3 scripts/freqUsed/building.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_9_3097_1.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_9_3097_1_floor.txt /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_9_3097_1_color.txt 0.07471521690261543
python3 scripts/freqUsed/building.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_18_11_1.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_18_11_1_floor.txt /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_18_11_1_color.txt 0.07471521690261543
python3 scripts/freqUsed/building.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_1_7607_4.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_1_7607_4_floor.txt /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_1_7607_4_color.txt 0.07471521690261543
python3 scripts/freqUsed/building.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_1_4738_30.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_1_4738_30_floor.txt /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_1_4738_30_color.txt 0.07471521690261543
python3 scripts/freqUsed/building.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_2_552_1.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_2_552_1_floor.txt /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_2_552_1_color.txt 0.07471521690261543
python3 scripts/freqUsed/building.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_32_3_1.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_32_3_1_floor.txt /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_32_3_1_color.txt 0.07471521690261543
python3 scripts/freqUsed/building.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_7_13363_2.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_7_13363_2_floor.txt /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_7_13363_2_color.txt 0.07471521690261543
python3 scripts/freqUsed/building.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_1_17795_20.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_1_17795_20_floor.txt /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_1_17795_20_color.txt 0.07471521690261543
python3 scripts/freqUsed/building.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_5_12699_1.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_5_12699_1_floor.txt /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_5_12699_1_color.txt 0.07471521690261543
python3 scripts/freqUsed/building.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_2_16614_1.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_2_16614_1_floor.txt /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_2_16614_1_color.txt 0.07471521690261543
python3 scripts/freqUsed/building.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_11_23_1.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_11_23_1_floor.txt /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_11_23_1_color.txt 0.07471521690261543
python3 scripts/freqUsed/building.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_76_87_1.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_76_87_1_floor.txt /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_76_87_1_color.txt 0.07471521690261543
python3 scripts/freqUsed/building.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_51_18_1.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_51_18_1_floor.txt /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_51_18_1_color.txt 0.07471521690261543
python3 scripts/freqUsed/building.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_8_3_1.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_8_3_1_floor.txt /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/wavemap_8_3_1_color.txt 0.07471521690261543
python3 scripts/freqUsed/bush.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_1_17795_1_19999.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/bushes.json
python3 scripts/freqUsed/bush.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_1_17795_1_3659.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/bushes.json
python3 scripts/freqUsed/bush.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_1_568_1_1.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/bushes.json
python3 scripts/freqUsed/bush.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_7_13363_7_20297.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/bushes.json
python3 scripts/freqUsed/bush.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_1_7607_1_13480.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/bushes.json
python3 scripts/freqUsed/bush.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_1_17795_1_7459.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/bushes.json
python3 scripts/freqUsed/bush.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_1_17795_1_661.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/bushes.json
python3 scripts/freqUsed/bush.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_1_17795_1_5544.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/bushes.json
python3 scripts/freqUsed/bush.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_1_4738_1_18215.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/bushes.json
python3 scripts/freqUsed/bush.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_1_4738_1_17865.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/bushes.json
python3 scripts/freqUsed/bush.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_1_4738_1_20277.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/bushes.json
python3 scripts/freqUsed/bush.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_1_4738_1_17986.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/bushes.json
python3 scripts/freqUsed/bush.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_1_568_1_2443.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/bushes.json
python3 scripts/freqUsed/bush.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_1_4738_1_12103.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/bushes.json
python3 scripts/freqUsed/bush.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_2_664_2_20524.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/bushes.json
python3 scripts/freqUsed/bush.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_1_7607_1_10500.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/bushes.json
python3 scripts/freqUsed/bush.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_1_17795_1_10526.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/bushes.json
python3 scripts/freqUsed/bush.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_1_4738_1_23301.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/bushes.json
python3 scripts/freqUsed/bush.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_1_17795_1_140.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/bushes.json
python3 scripts/freqUsed/bush.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_1_7607_1_4025.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/bushes.json
python3 scripts/freqUsed/bush.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_1_4738_1_2872.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/bushes.json
python3 scripts/freqUsed/bush.py /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/stackoverflow_electronics_waves/wavemap_1_568_1_3993.json /common/home/da865/Desktop/StackOverflow/Graph-Cities/wave-decomposition/stackoverflow_electronics/cityMesh/bushes.json
